# Generated by Django 6.0.7 on 2026-09-05 08:17

import apps.barbers.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0017_club_category_alter_branchimage_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('affiliation_status', models.CharField(choices=[('NONE', 'Birikmagan'), ('PENDING', 'Tasdiq kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], default='NONE', help_text='Sartaroshxonaga birikish holati.', max_length=15)),
                ('full_name', models.CharField(help_text="Sartaroshning to'liq ismi.", max_length=180)),
                ('phone', models.CharField(blank=True, help_text='Aloqa telefoni.', max_length=20)),
                ('photo', models.ImageField(blank=True, help_text='Sartaroshning fotosurati.', upload_to=apps.barbers.models.barber_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'), code='barbers.invalid_image_format', message='barbers.invalid_image_format')])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Ishda'), ('BREAK', 'Tanaffusda'), ('NOT_AT_WORK', 'Ishga chiqmagan'), ('DAY_OFF', 'Dam olish kuni')], default='AVAILABLE', help_text='Real vaqt holati (Ishda, Tanaffusda, Ishga chiqmagan, Dam olish kuni).', max_length=20)),
                ('work_start_time', models.TimeField(default='09:00', help_text='Ish boshlanish vaqti.')),
                ('work_end_time', models.TimeField(default='20:00', help_text='Ish tugash vaqti.')),
                ('working_days', models.JSONField(blank=True, default=list, help_text="Ish kunlari ro'yxati (1=Dushanba ... 7=Yakshanba).")),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sartarosh reytingi.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.PositiveIntegerField(default=0, help_text='Sharhlar soni.')),
                ('is_active', models.BooleanField(default=True, help_text='Faollik holati.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Sartaroshxona filiali.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbers', to='clubs.branch')),
                ('club', models.ForeignKey(blank=True, help_text='Sartaroshxona.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbers', to='clubs.club')),
                ('user', models.OneToOneField(help_text='Sartarosh foydalanuvchi akkaunti.', on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'barbers',
                'ordering': ('-rating', '-created_at'),
            },
        ),
    ]
