# Generated by Django 6.0.7 on 2026-10-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
        ('clubs', '0021_add_general_booking_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='billing_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_barbers', to='clubs.city'),
        ),
        migrations.AddField(
            model_name='barber',
            name='billing_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_barbers', to='clubs.district'),
        ),
    ]
