# Generated by Django 6.0.7 on 2026-10-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_independent_barber_billing_and_free_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Platformadan bepul foydalanish.'),
        ),
    ]
