# Generated by Django 6.0.7 on 2026-07-26 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='1005', message='1005', regex='^[a-zA-Z0-9_]{1,30}$')]),
        ),
    ]
