# Generated by Django 6.0.7 on 2026-07-28 18:41

from django.db import migrations, models


def normalize_removed_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(
        role__in=("CLUB_OPERATOR", "CLUB_MANAGER"),
    ).update(role="CUSTOMER")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RunPython(
            normalize_removed_roles,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Administrator')], default='CUSTOMER', max_length=20),
        ),
    ]
