# Generated by Django 6.0.7 on 2026-08-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_telegram_identity'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otprequest',
            name='otp_phone_purpose_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='otprequest',
            name='otp_expires_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='otprequest',
            name='otp_phone_created_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sms_notifications_enabled',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='OTPRequest',
        ),
    ]
