# Generated by Django 6.0.7 on 2026-09-05 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_telegram_only_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='auth.invalid_phone_format', message='auth.invalid_phone_format', regex='^\\+?[1-9]\\d{7,14}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='auth.invalid_username_format', message='auth.invalid_username_format', regex='^[a-zA-Z0-9_]{1,30}$')]),
        ),
    ]
