# Generated by Django 6.0.7 on 2026-10-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_password_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('CLIENT', 'Client'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Administrator')], default='CUSTOMER', max_length=20),
        ),
    ]
