# Generated by Django 6.0.7 on 2026-08-17 09:50

import apps.core.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperBotSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('bot_token', apps.core.fields.EncryptedTextField(blank=True)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('environment', models.CharField(default='development', max_length=50)),
                ('request_timeout_seconds', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('notify_errors', models.BooleanField(default=True)),
                ('notify_user_events', models.BooleanField(default=True)),
                ('notify_booking_events', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Developer bot settings',
                'db_table': 'developer_bot_settings',
            },
        ),
    ]
