# Generated by Django 6.0.7 on 2026-09-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptranslation',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='systemmessage',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
