# Generated by Django 6.0.7 on 2026-07-26 16:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'db_table': 'club_amenities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=12)),
                ('specifications', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'club_computers',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=210, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending moderation'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clubs',
                'ordering': ('-is_verified', '-rating', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('district', models.CharField(blank=True, db_index=True, max_length=120)),
                ('landmark', models.CharField(blank=True, max_length=250)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('TEMP_CLOSED', 'Temporarily closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)),
                ('booking_mode', models.CharField(choices=[('ZONE', 'By zone'), ('COMPUTER', 'By computer')], default='ZONE', max_length=10)),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)])),
                ('minimum_booking_minutes', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1440)])),
                ('maximum_booking_minutes', models.PositiveSmallIntegerField(default=720, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1440)])),
                ('booking_hold_minutes', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('advance_booking_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('free_cancellation_minutes', models.PositiveIntegerField(default=180)),
                ('no_show_grace_minutes', models.PositiveSmallIntegerField(default=20)),
                ('auto_confirm_booking', models.BooleanField(default=True)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('amenities', models.ManyToManyField(blank=True, related_name='branches', to='clubs.amenity')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='clubs.club')),
            ],
            options={
                'db_table': 'club_branches',
                'ordering': ('club__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ClubStaff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('OPERATOR', 'Operator')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='clubs.branch')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'club_staff',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_clubs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OperatingHour',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='clubs.branch')),
            ],
            options={
                'db_table': 'branch_operating_hours',
                'ordering': ('weekday',),
            },
        ),
        migrations.CreateModel(
            name='SpecialSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_schedules', to='clubs.branch')),
            ],
            options={
                'db_table': 'branch_special_schedules',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=12)),
                ('capacity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('cpu', models.CharField(blank=True, max_length=120)),
                ('gpu', models.CharField(blank=True, max_length=120)),
                ('ram', models.CharField(blank=True, max_length=120)),
                ('monitor', models.CharField(blank=True, max_length=120)),
                ('peripherals', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='clubs.branch')),
            ],
            options={
                'db_table': 'club_zones',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valid_weekdays', models.JSONField(blank=True, default=list)),
                ('starts_at', models.TimeField(blank=True, null=True)),
                ('ends_at', models.TimeField(blank=True, null=True)),
                ('minimum_minutes', models.PositiveSmallIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='clubs.zone')),
            ],
            options={
                'db_table': 'club_tariffs',
                'ordering': ('price_per_hour', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ResourceBlock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('computer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_blocks', to='clubs.computer')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_blocks', to='clubs.zone')),
            ],
            options={
                'db_table': 'club_resource_blocks',
                'ordering': ('starts_at',),
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='clubs.zone'),
        ),
        migrations.CreateModel(
            name='BranchImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clubs.branch')),
            ],
            options={
                'db_table': 'branch_images',
                'ordering': ('sort_order', 'created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('branch',), name='one_cover_image_per_branch')],
            },
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['status', 'rating'], name='club_status_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['owner', 'status'], name='club_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['status', 'city'], name='branch_status_city_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['latitude', 'longitude'], name='branch_geo_idx'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('club', 'name'), name='unique_branch_name_per_club'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_booking_minutes__gte', models.F('minimum_booking_minutes'))), name='branch_max_booking_gte_min'),
        ),
        migrations.AddIndex(
            model_name='clubstaff',
            index=models.Index(fields=['user', 'is_active'], name='staff_user_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='clubstaff',
            constraint=models.UniqueConstraint(fields=('club', 'user', 'branch'), name='unique_club_staff_assignment', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'club'), name='unique_user_favorite_club'),
        ),
        migrations.AddConstraint(
            model_name='operatinghour',
            constraint=models.UniqueConstraint(fields=('branch', 'weekday'), name='unique_branch_weekday'),
        ),
        migrations.AddConstraint(
            model_name='specialschedule',
            constraint=models.UniqueConstraint(fields=('branch', 'date'), name='unique_branch_special_date'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['branch', 'status'], name='zone_branch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_zone_name_per_branch'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['zone', 'is_active'], name='tariff_zone_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.UniqueConstraint(fields=('zone', 'name'), name='unique_tariff_name_per_zone'),
        ),
        migrations.AddIndex(
            model_name='resourceblock',
            index=models.Index(fields=['zone', 'starts_at', 'ends_at'], name='block_zone_time_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceblock',
            index=models.Index(fields=['computer', 'starts_at', 'ends_at'], name='block_pc_time_idx'),
        ),
        migrations.AddIndex(
            model_name='computer',
            index=models.Index(fields=['zone', 'status'], name='computer_zone_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='computer',
            constraint=models.UniqueConstraint(fields=('zone', 'code'), name='unique_computer_code_per_zone'),
        ),
    ]
