# Generated by Django 6.0.7 on 2026-07-26 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clubstaff',
            name='unique_club_staff_assignment',
        ),
        migrations.AddConstraint(
            model_name='clubstaff',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('club', 'user'), name='unique_global_club_staff'),
        ),
        migrations.AddConstraint(
            model_name='clubstaff',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('club', 'user', 'branch'), name='unique_branch_club_staff'),
        ),
    ]
