# Generated by Django 6.0.7 on 2026-07-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_clubstaff_unique_club_staff_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='computer',
            name='computer_zone_status_idx',
        ),
        migrations.RemoveConstraint(
            model_name='computer',
            name='unique_computer_code_per_zone',
        ),
        migrations.RemoveIndex(
            model_name='resourceblock',
            name='block_pc_time_idx',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='booking_mode',
        ),
        migrations.RemoveField(
            model_name='resourceblock',
            name='computer',
        ),
        migrations.DeleteModel(
            name='Computer',
        ),
    ]
