# Generated by Django 6.0.7 on 2026-07-26 18:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_remove_zone_specifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ('club__name', 'name'), 'verbose_name': 'Klub filiali', 'verbose_name_plural': 'Klub filiallari'},
        ),
        migrations.AlterModelOptions(
            name='branchimage',
            options={'ordering': ('sort_order', 'created_at'), 'verbose_name': 'Filial rasmi', 'verbose_name_plural': 'Filial rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ('-is_verified', '-rating', 'name'), 'verbose_name': 'O‘yin klubi', 'verbose_name_plural': 'O‘yin klublari'},
        ),
        migrations.AlterModelOptions(
            name='clubstaff',
            options={'verbose_name': 'Klub xodimi', 'verbose_name_plural': 'Klub xodimlari'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-created_at',), 'verbose_name': 'Sevimli klub', 'verbose_name_plural': 'Sevimli klublar'},
        ),
        migrations.AlterModelOptions(
            name='operatinghour',
            options={'ordering': ('weekday',), 'verbose_name': 'Ish vaqti', 'verbose_name_plural': 'Ish vaqtlari'},
        ),
        migrations.AlterModelOptions(
            name='resourceblock',
            options={'ordering': ('starts_at',), 'verbose_name': 'Zona blokirovkasi', 'verbose_name_plural': 'Zona blokirovkalari'},
        ),
        migrations.AlterModelOptions(
            name='specialschedule',
            options={'ordering': ('date',), 'verbose_name': 'Maxsus ish jadvali', 'verbose_name_plural': 'Maxsus ish jadvallari'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ('price_per_hour_tiyin', 'name'), 'verbose_name': 'Tarif', 'verbose_name_plural': 'Tariflar'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'O‘yin zonasi', 'verbose_name_plural': 'O‘yin zonalari'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(help_text='To‘liq manzil.', max_length=300),
        ),
        migrations.AlterField(
            model_name='branch',
            name='advance_booking_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Oldindan bron qilish kunlari.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='auto_confirm_booking',
            field=models.BooleanField(default=True, help_text='Bron avtomatik tasdiqlanadimi.'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='booking_hold_minutes',
            field=models.PositiveSmallIntegerField(default=7, help_text='Joyni ushlab turish vaqti.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(db_index=True, help_text='Shahar nomi.', max_length=120),
        ),
        migrations.AlterField(
            model_name='branch',
            name='club',
            field=models.ForeignKey(help_text='Filial tegishli klub.', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, help_text='Filial tavsifi.'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='district',
            field=models.CharField(blank=True, db_index=True, help_text='Tuman nomi.', max_length=120),
        ),
        migrations.AlterField(
            model_name='branch',
            name='free_cancellation_minutes',
            field=models.PositiveIntegerField(default=180, help_text='Bepul bekor qilish muddati.'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_24_hours',
            field=models.BooleanField(default=False, help_text='Filial 24/7 ishlaydimi.'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='landmark',
            field=models.CharField(blank=True, help_text='Mo‘ljal.', max_length=250),
        ),
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='Xarita kengligi.', max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(decimal_places=6, help_text='Xarita uzunligi.', max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='maximum_booking_minutes',
            field=models.PositiveSmallIntegerField(default=720, help_text='Maksimal bron vaqti.', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='minimum_booking_minutes',
            field=models.PositiveSmallIntegerField(default=60, help_text='Minimal bron vaqti.', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(help_text='Filial nomi.', max_length=180),
        ),
        migrations.AlterField(
            model_name='branch',
            name='no_show_grace_minutes',
            field=models.PositiveSmallIntegerField(default=20, help_text='Kechikish uchun kutish vaqti.'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, help_text='Filial telefoni.', max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='slot_interval_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='Bron vaqt qadami, daqiqada.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('TEMP_CLOSED', 'Temporarily closed'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Filial holati.', max_length=12),
        ),
        migrations.AlterField(
            model_name='branch',
            name='timezone',
            field=models.CharField(default='Asia/Tashkent', help_text='Vaqt mintaqasi.', max_length=64),
        ),
        migrations.AlterField(
            model_name='branchimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Rasm izohi.', max_length=180),
        ),
        migrations.AlterField(
            model_name='branchimage',
            name='branch',
            field=models.ForeignKey(help_text='Rasm tegishli filial.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clubs.branch'),
        ),
        migrations.AlterField(
            model_name='branchimage',
            name='image_url',
            field=models.URLField(help_text='Rasm havolasi.', max_length=500),
        ),
        migrations.AlterField(
            model_name='branchimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='Asosiy rasmmi.'),
        ),
        migrations.AlterField(
            model_name='branchimage',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ko‘rinish tartibi.'),
        ),
        migrations.AlterField(
            model_name='club',
            name='cover_url',
            field=models.URLField(blank=True, help_text='Muqova rasmi havolasi.', max_length=500),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, help_text='Klub tavsifi.'),
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, help_text='Aloqa emaili.', max_length=254),
        ),
        migrations.AlterField(
            model_name='club',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Tekshiruvdan o‘tganmi.'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Logo havolasi.', max_length=500),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(help_text='Klub nomi.', max_length=180),
        ),
        migrations.AlterField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(help_text='Klub egasi.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='phone',
            field=models.CharField(blank=True, help_text='Aloqa telefoni.', max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='O‘rtacha reyting.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='club',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text='Izohlar soni.'),
        ),
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(help_text='URL uchun nom.', max_length=210, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending moderation'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Klub holati.', max_length=12),
        ),
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, help_text='Klub sayti.', max_length=500),
        ),
        migrations.AlterField(
            model_name='clubstaff',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Biriktirilgan filial.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='clubs.branch'),
        ),
        migrations.AlterField(
            model_name='clubstaff',
            name='club',
            field=models.ForeignKey(help_text='Xodim ishlaydigan klub.', on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='clubstaff',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Xodim faolmi.'),
        ),
        migrations.AlterField(
            model_name='clubstaff',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('OPERATOR', 'Operator')], help_text='Xodim roli.', max_length=10),
        ),
        migrations.AlterField(
            model_name='clubstaff',
            name='user',
            field=models.ForeignKey(help_text='Tizim foydalanuvchisi.', on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='club',
            field=models.ForeignKey(help_text='Sevimli klub.', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(help_text='Sevimliga qo‘shgan foydalanuvchi.', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operatinghour',
            name='branch',
            field=models.ForeignKey(help_text='Ish vaqti tegishli filial.', on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='clubs.branch'),
        ),
        migrations.AlterField(
            model_name='operatinghour',
            name='closes_at',
            field=models.TimeField(blank=True, help_text='Yopilish vaqti.', null=True),
        ),
        migrations.AlterField(
            model_name='operatinghour',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Dam olish kunimi.'),
        ),
        migrations.AlterField(
            model_name='operatinghour',
            name='opens_at',
            field=models.TimeField(blank=True, help_text='Ochilish vaqti.', null=True),
        ),
        migrations.AlterField(
            model_name='operatinghour',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Hafta kuni.'),
        ),
        migrations.AlterField(
            model_name='resourceblock',
            name='ends_at',
            field=models.DateTimeField(help_text='Blok tugash vaqti.'),
        ),
        migrations.AlterField(
            model_name='resourceblock',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Blok faolmi.'),
        ),
        migrations.AlterField(
            model_name='resourceblock',
            name='reason',
            field=models.CharField(help_text='Bloklash sababi.', max_length=250),
        ),
        migrations.AlterField(
            model_name='resourceblock',
            name='starts_at',
            field=models.DateTimeField(help_text='Blok boshlanish vaqti.'),
        ),
        migrations.AlterField(
            model_name='resourceblock',
            name='zone',
            field=models.ForeignKey(help_text='Blok tegishli zona.', on_delete=django.db.models.deletion.CASCADE, related_name='resource_blocks', to='clubs.zone'),
        ),
        migrations.AlterField(
            model_name='specialschedule',
            name='branch',
            field=models.ForeignKey(help_text='Jadval tegishli filial.', on_delete=django.db.models.deletion.CASCADE, related_name='special_schedules', to='clubs.branch'),
        ),
        migrations.AlterField(
            model_name='specialschedule',
            name='closes_at',
            field=models.TimeField(blank=True, help_text='Yopilish vaqti.', null=True),
        ),
        migrations.AlterField(
            model_name='specialschedule',
            name='date',
            field=models.DateField(help_text='Maxsus sana.'),
        ),
        migrations.AlterField(
            model_name='specialschedule',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Filial yopiqmi.'),
        ),
        migrations.AlterField(
            model_name='specialschedule',
            name='note',
            field=models.CharField(blank=True, help_text='Qo‘shimcha izoh.', max_length=250),
        ),
        migrations.AlterField(
            model_name='specialschedule',
            name='opens_at',
            field=models.TimeField(blank=True, help_text='Ochilish vaqti.', null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='ends_at',
            field=models.TimeField(blank=True, help_text='Tugash vaqti.', null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Tarif faolmi.'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='minimum_minutes',
            field=models.PositiveSmallIntegerField(default=60, help_text='Minimal foydalanish vaqti.'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(help_text='Tarif nomi.', max_length=120),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_per_hour_tiyin',
            field=models.PositiveBigIntegerField(help_text='Bir soat narxi, tiyinlarda.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='starts_at',
            field=models.TimeField(blank=True, help_text='Boshlanish vaqti.', null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='valid_weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Amal qiladigan hafta kunlari.'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='zone',
            field=models.ForeignKey(help_text='Tarif tegishli zona.', on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='clubs.zone'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='branch',
            field=models.ForeignKey(help_text='Zona tegishli filial.', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='clubs.branch'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Bir vaqtdagi joylar soni.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True, help_text='Zona tavsifi.'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(help_text='Zona nomi.', max_length=120),
        ),
        migrations.AlterField(
            model_name='zone',
            name='resource_type',
            field=models.CharField(choices=[('COMPUTER', 'Computer'), ('PLAYSTATION', 'PlayStation')], default='COMPUTER', help_text='O‘yin qurilmasi turi.', max_length=12),
        ),
        migrations.AlterField(
            model_name='zone',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ko‘rinish tartibi.'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('DISABLED', 'Disabled')], default='ACTIVE', help_text='Zona holati.', max_length=12),
        ),
    ]
