# Generated by Django 6.0.7 on 2026-07-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_branch_options_alter_branchimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchimage',
            name='alt_text',
        ),
        migrations.AlterField(
            model_name='operatinghour',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Yopilgan'),
        ),
    ]
