# Generated by Django 6.0.7 on 2026-07-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_move_price_to_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ('-is_verified', '-rating', 'name'), 'verbose_name': 'Klub', 'verbose_name_plural': 'Klublar'},
        ),
    ]
