# Generated by Django 6.0.7 on 2026-07-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_seed_uzbekistan_cities'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clubstaff',
            name='staff_user_active_idx',
        ),
        migrations.RemoveConstraint(
            model_name='clubstaff',
            name='unique_global_club_staff',
        ),
        migrations.RemoveConstraint(
            model_name='clubstaff',
            name='unique_branch_club_staff',
        ),
        migrations.DeleteModel(
            name='ClubStaff',
        ),
    ]
