# Generated by Django 6.0.7 on 2026-07-28 19:20

from django.db import migrations, models


def set_cancellation_window(apps, schema_editor):
    Branch = apps.get_model("clubs", "Branch")
    Branch.objects.update(free_cancellation_minutes=60)


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_remove_club_staff'),
    ]

    operations = [
        migrations.RunPython(
            set_cancellation_window,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='branch',
            name='free_cancellation_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Bepul bekor qilish muddati.'),
        ),
    ]
