# Generated by Django 6.0.7 on 2026-09-05 08:17

import apps.clubs.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_add_zone_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('GAMING_CLUB', 'Gaming Club'), ('BARBERSHOP', 'Barbershop')], default='GAMING_CLUB', help_text='Muassasa toifasi.', max_length=20),
        ),
        migrations.AlterField(
            model_name='branchimage',
            name='image',
            field=models.ImageField(help_text='Filial rasmi.', upload_to=apps.clubs.models.branch_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'), code='clubs.invalid_image_format', message='clubs.invalid_image_format'), apps.clubs.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='club',
            name='cover',
            field=models.ImageField(blank=True, help_text='Klub muqova rasmi.', upload_to=apps.clubs.models.club_cover_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'), code='clubs.invalid_image_format', message='clubs.invalid_image_format'), apps.clubs.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, help_text='Klub logotipi.', upload_to=apps.clubs.models.club_logo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'), code='clubs.invalid_image_format', message='clubs.invalid_image_format'), apps.clubs.models.validate_image_size]),
        ),
    ]
