# Generated by Django 6.0.7 on 2026-10-01 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_club_category_alter_branchimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='address',
            field=models.CharField(blank=True, help_text="Klub manzili (qo'lda kiritilgan).", max_length=300),
        ),
        migrations.AddField(
            model_name='club',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Xarita kengligi.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='club',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Xarita uzunligi.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
