# Generated by Django 6.0.7 on 2026-10-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_club_category_alter_branchimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='service_name',
            field=models.CharField(blank=True, help_text='Boshqa xizmat nomi.', max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('GAMING_CLUB', 'Gaming Club'), ('BARBERSHOP', 'Barbershop'), ('BILLIARDS', 'Billiards'), ('OTHER', 'Other')], default='GAMING_CLUB', help_text='Muassasa toifasi.', max_length=20),
        ),
    ]
