# Generated by Django 6.0.7 on 2026-10-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_add_flexible_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='billing_required',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
