# Generated by Django 6.0.7 on 2026-10-04 16:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_services(apps, schema_editor):
    Service = apps.get_model("clubs", "ServiceType")
    services = [("GAMING_CLUB", "O‘yin klubi"), ("BARBERSHOP", "Sartaroshxona"), ("BILLIARDS", "Bilyard"), ("GYM", "Sport zali"), ("FOOTBALL", "Futbol maydoni"), ("POOL", "Basseyn"), ("CAR_WASH", "Avtoyuvish"), ("BEAUTY", "Go‘zallik saloni"), ("COWORKING", "Kovorking"), ("PHOTO_STUDIO", "Fotostudiya"), ("EVENT_HALL", "Tadbirlar zali"), ("OTHER", "Boshqa xizmat")]
    for order, (code, name) in enumerate(services):
        Service.objects.get_or_create(code=code, defaults={"name": name, "sort_order": order})
    # Keep existing venues on their established prices until explicitly assigned
    # to the regional catalogue; no paid period or historical tariff is changed.


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_require_billing_for_new_venues'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Xizmat turi',
                'verbose_name_plural': 'Xizmat turlari',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='club',
            name='billing_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_clubs', to='clubs.city'),
        ),
        migrations.AddField(
            model_name='club',
            name='billing_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_clubs', to='clubs.district'),
        ),
        migrations.AddField(
            model_name='club',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clubs.servicetype'),
        ),
        migrations.RunPython(seed_services, migrations.RunPython.noop),
    ]
