# Generated by Django 6.0.7 on 2026-10-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_dynamic_services_and_regional_tariffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='booking_type',
            field=models.CharField(choices=[('PER_SEAT', 'Har bir joy uchun'), ('PER_ZONE', 'Butun resurs uchun')], default='PER_SEAT', help_text='Narx har bir joy yoki butun xona uchun hisoblanishi.', max_length=8),
        ),
        migrations.AlterField(
            model_name='zone',
            name='resource_type',
            field=models.CharField(choices=[('GENERAL', 'Resurs'), ('COMPUTER', 'Computer'), ('PLAYSTATION', 'PlayStation')], default='GENERAL', help_text='O‘yin qurilmasi turi.', max_length=12),
        ),
    ]
