# Generated by Django 6.0.7 on 2026-10-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_add_general_booking_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Platformadan bepul foydalanish.'),
        ),
    ]
