# Generated by Django 6.0.7 on 2026-10-04 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_club_category_alter_branchimage_image_and_more'),
        ('payments', '0002_add_payment_checkout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_price_tiyin', models.PositiveBigIntegerField()),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing', to='clubs.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManualVenuePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_tiyin', models.PositiveBigIntegerField()),
                ('monthly_price_tiyin', models.PositiveBigIntegerField()),
                ('method', models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Karta')], max_length=4)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('period_starts_at', models.DateTimeField()),
                ('period_ends_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venue_payments', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collected_venue_payments', to=settings.AUTH_USER_MODEL)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.venuebilling')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='venuebilling',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_price_tiyin__gt', 0)), name='venue_billing_positive_price'),
        ),
        migrations.AddConstraint(
            model_name='manualvenuepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_tiyin__gt', 0)), name='manual_venue_payment_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='manualvenuepayment',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_price_tiyin__gt', 0)), name='manual_venue_payment_positive_price'),
        ),
        migrations.AddConstraint(
            model_name='manualvenuepayment',
            constraint=models.CheckConstraint(condition=models.Q(('period_ends_at__gt', models.F('period_starts_at'))), name='manual_venue_payment_positive_period'),
        ),
        migrations.AddConstraint(
            model_name='manualvenuepayment',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ('CASH', 'CARD'))), name='manual_venue_payment_valid_method'),
        ),
    ]
