# Generated by Django 6.0.7 on 2026-10-04 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_dynamic_services_and_regional_tariffs'),
        ('payments', '0003_add_manual_venue_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueTariffRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price_tiyin', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clubs.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clubs.district')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.servicetype')),
            ],
            options={
                'verbose_name': 'Hudud va xizmat tarifi',
                'verbose_name_plural': 'Hudud va xizmat tariflari',
                'constraints': [models.UniqueConstraint(condition=models.Q(('district__isnull', False)), fields=('service_type', 'district'), name='venue_tariff_district_unique'), models.UniqueConstraint(condition=models.Q(('city__isnull', False), ('district__isnull', True)), fields=('service_type', 'city'), name='venue_tariff_city_unique'), models.UniqueConstraint(condition=models.Q(('city__isnull', True), ('district__isnull', True)), fields=('service_type',), name='venue_tariff_default_unique')],
            },
        ),
    ]
