# Generated by Django 6.0.7 on 2026-10-04 17:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_launch_settings(apps, schema_editor):
    apps.get_model("payments", "PlatformBillingSettings").objects.get_or_create(pk=1)
    apps.get_model("clubs", "ServiceType").objects.get_or_create(code="BARBER", defaults={"name": "Sartarosh", "sort_order": 2})


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_independent_barber_billing_and_free_mode'),
        ('payments', '0004_dynamic_services_and_regional_tariffs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBillingSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('paid_mode_enabled', models.BooleanField(default=False, verbose_name='Pullik rejim yoqilgan')),
                ('grace_days', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pullik rejimga o‘tish uchun kunlar')),
                ('paid_mode_started_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Platforma to‘lov rejimi',
                'verbose_name_plural': 'Platforma to‘lov rejimi',
            },
        ),
        migrations.AlterField(
            model_name='manualvenuepayment',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.venuebilling'),
        ),
        migrations.CreateModel(
            name='BarberBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_price_tiyin', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing', to='barbers.barber')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='manualvenuepayment',
            name='barber_billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.barberbilling'),
        ),
        migrations.AddConstraint(
            model_name='manualvenuepayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('barber_billing__isnull', True), ('billing__isnull', False)), models.Q(('barber_billing__isnull', False), ('billing__isnull', True)), _connector='OR'), name='manual_payment_single_target'),
        ),
        migrations.AddConstraint(
            model_name='platformbillingsettings',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='platform_billing_singleton'),
        ),
        migrations.AddConstraint(
            model_name='barberbilling',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_price_tiyin__gt', 0)), name='barber_billing_positive_price'),
        ),
        migrations.RunPython(seed_launch_settings, migrations.RunPython.noop),
    ]
