# Generated by Django 6.0.7 on 2026-08-01 06:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_cancellation_actor_name_cancellation_source_and_more'),
        ('clubs', '0015_set_cancellation_window_to_one_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telegram_groups',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TelegramMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('PENDING', 'Pending booking'), ('CONFIRMED', 'Confirmed booking'), ('CANCELLED', 'Cancelled booking')], max_length=20, unique=True)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telegram_message_templates',
            },
        ),
        migrations.CreateModel(
            name='TelegramBookingMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('operation', models.CharField(choices=[('SEND', 'Send'), ('EDIT', 'Edit')], default='SEND', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('acted_by_telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('acted_by_name', models.CharField(blank=True, max_length=150)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_message', to='bookings.booking')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram_bot.telegramgroup')),
            ],
            options={
                'db_table': 'telegram_booking_messages',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='BranchTelegramBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_binding', to='clubs.branch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_bindings', to='telegram_bot.telegramgroup')),
            ],
            options={
                'db_table': 'branch_telegram_bindings',
            },
        ),
    ]
