# Generated by Django 6.0.7 on 2026-08-17 09:50

import apps.core.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_dynamic_settings_and_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotsettings',
            name='bot_token',
            field=apps.core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='telegrambotsettings',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrambotsettings',
            name='polling_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='telegrambotsettings',
            name='request_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='telegrambotsettings',
            name='retry_delay_seconds',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='telegrambotsettings',
            name='test_group_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
