# Generated by Django 6.0.7 on 2026-07-28 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0013_seed_uzbekistan_cities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHold',
            fields=[
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price_tiyin', models.PositiveBigIntegerField()),
                ('total_price_tiyin', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('CONVERTED', 'Converted'), ('EXPIRED', 'Expired')], default='HELD', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.zone')),
            ],
            options={
                'db_table': 'booking_holds',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price_tiyin', models.PositiveBigIntegerField()),
                ('total_price_tiyin', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('HELD', 'Held'), ('PAYMENT_PENDING', 'Payment pending'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked in'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('PAYMENT_FAILED', 'Payment failed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No-show'), ('REFUND_PENDING', 'Refund pending'), ('REFUNDED', 'Refunded')], default='HELD', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.zone')),
                ('hold', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='bookings.bookinghold')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('refund_amount_tiyin', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation', to='bookings.booking')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_cancellations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='bookinghold',
            index=models.Index(fields=['zone', 'starts_at', 'ends_at', 'status'], name='hold_zone_time_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinghold',
            index=models.Index(fields=['user', 'status', 'expires_at'], name='hold_user_status_exp_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookinghold',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='hold_ends_after_start'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['zone', 'starts_at', 'ends_at', 'status'], name='booking_zone_time_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status', 'starts_at'], name='booking_user_status_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='booking_ends_after_start'),
        ),
    ]
