# Generated by Django 6.0.7 on 2026-07-28 19:20

from django.db import migrations, models


def normalize_booking_statuses(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    Booking.objects.filter(
        status__in=("DRAFT", "HELD", "PAYMENT_PENDING"),
    ).update(status="CONFIRMED")
    Booking.objects.filter(
        status__in=("EXPIRED", "PAYMENT_FAILED", "REFUND_PENDING", "REFUNDED"),
    ).update(status="CANCELLED")


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_add_booking_core'),
    ]

    operations = [
        migrations.RunPython(
            normalize_booking_statuses,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='cancellation',
            name='refund_amount_tiyin',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked in'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No-show')], default='CONFIRMED', max_length=20),
        ),
    ]
