# Generated by Django 6.0.7 on 2026-08-01 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_add_booking_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='actor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='source',
            field=models.CharField(choices=[('USER', 'User'), ('TELEGRAM', 'Telegram')], default='USER', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING_CONFIRMATION', 'Pending confirmation'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked in'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No-show')], default='PENDING_CONFIRMATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='cancellation',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
