# Generated by Django 6.0.7 on 2026-09-05 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '__first__'),
        ('bookings', '0005_add_booking_lifecycle_timestamps'),
        ('clubs', '0017_club_category_alter_branchimage_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='barbers.barber'),
        ),
        migrations.AddField(
            model_name='bookinghold',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='barbers.barber'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hold',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='bookings.bookinghold'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price_tiyin',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='unit_price_tiyin',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clubs.zone'),
        ),
        migrations.AlterField(
            model_name='bookinghold',
            name='total_price_tiyin',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookinghold',
            name='unit_price_tiyin',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookinghold',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clubs.zone'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['barber', 'starts_at', 'ends_at', 'status'], name='booking_barber_time_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinghold',
            index=models.Index(fields=['barber', 'starts_at', 'ends_at', 'status'], name='hold_barber_time_status_idx'),
        ),
    ]
