# Generated by Django 6.0.7 on 2026-09-05 08:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '__first__'),
        ('bookings', '0006_booking_barber_bookinghold_barber_alter_booking_hold_and_more'),
        ('clubs', '0017_club_category_alter_branchimage_image_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='barbers.barber'),
        ),
        migrations.AddField(
            model_name='review',
            name='barber_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='reviews.rating_invalid'), django.core.validators.MaxValueValidator(5, message='reviews.rating_invalid')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='reviews.rating_invalid'), django.core.validators.MaxValueValidator(5, message='reviews.rating_invalid')]),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['barber', 'is_visible', 'created_at'], name='review_barber_visible_idx'),
        ),
    ]
